export default {
    EMP_LOGIN_TITLE: 'Employee',
    DRIVER_LOGIN_TITLE: 'Driver',
    ADMIN_LOGIN_TITLE: 'Admin',
    DRIVER_REG_TITLE: 'Register',
    REG_BTN_TITLE: 'Register',
    BOOK_BTN_TITLE: 'Book Cab',
    OKTA_LOGIN: 'Login with Okta',
    REVOKE_BTN_TITLE: 'Revoke',
    VEHICLEINPUT: 'DL/Phone/Vehicle',
    DRIVER_LOGIN: 'SignIn using OTP',
    DRIVER_NAME: 'Driver First Name',
    DRIVER_PHONE: 'Phone Number',
    DRIVER_VEHICLE: 'Vehicle Number',
    DRIVER_LICENSE: 'License',
    DRIVER_ADDRESS: 'Address',
    ENTER_OTP: 'Enter OTP',
    CANCEL_PICK: 'Delete Trip',
    CANCEL_DROP: 'Cancel Drop',
    DESC_TITLE: 'Enter Time Change Request',
    SUBMIT_REQUEST: 'Update',
    CANCEL_REQUEST: 'Cancel',
    CANCEL_TRIP: 'Cancel Trip',
    UPDATE_TRIP: 'Update Trip',
    UPDATE_DROP: 'Update Drop',
    UPDATE_PICK: 'Update Pickup',
    LOGOUT: 'Signout',
    LOGIN_BTN_ADMIN: 'Login',
    LOGOUT_BTN_ADMIN: 'Logout',
    DRIVER_LIST_ADMIN: 'Driver List',
    EMPLOYEE_LIST_ADMIN: 'Employee List',
    ASSIGN_TRIP: 'Assign Driver',
    BOOKED: 'Booked',
    REMOVE_DRIVER: 'Remove Driver',
    SEARCH_EMP: 'Go',
    EMP_BTN: 'Employee',
    UPDATE_TIME: 'Update Time',
    SIGNUP_BTN: 'Update',
    SUB_LINE: 'Enter Subject',
    UPDATE: 'Update',
    CANCELSTATUS: 'CANCELLED',
    SIGNUP_ADMIN: 'CREATE',
    DEL_ROSTER: 'DELETE ROSTER',
    UPDATE_ROSTER: 'UPDATE ROSTER',
    SET_DEFAULT: 'SET AS DEFAULT',
    PHONE_NUM: 'PHONE NUMBER',
    EMERGENCY_CONTACT: 'EMERGENCY CONTACT',
    HOME_ADDR: 'HOME ADDRESS',
    SEND_OTP: 'SEND OTP'
}